spring:
  application:
    name: LoginSys
    #数据库
  datasource:
    url: jdbc:mysql://106.12.127.134:3306/testdb?setUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
mybatis:
  config-location: classpath:config/mybatisConfig.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.ccc.loginsys.dao

server:
  port: 8002
  
 